version: '3.8'

services:
  vue-app:
    build: .
    ports:
      # - "8080:80"
      - "5173:80"
    container_name: hailoka-frontend
    networks:
      - hailoka-network

networks:
  hailoka-network:
    driver: bridge
